# Generated by Django 4.1.5 on 2023-01-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('deadline_time', models.DateTimeField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('interval', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id_ed', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('deadline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('lesson_number', models.SmallIntegerField()),
                ('subject', models.TextField(null=True)),
                ('auditorium', models.TextField(null=True)),
                ('teacher', models.TextField(null=True)),
                ('id_chat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk', models.IntegerField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('domain', models.TextField()),
                ('id_chat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.editor')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.table')),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.table'),
        ),
    ]
